@startuml

actor Client
participant "ODA Time Booking" as ODA
participant "EHR/AVPH FHIR Service" as av
participant "EHR Schedule Service" as EHR

Client -> ODA

ODA -> av : Search schedules with serviceproduct code
av <-> EHR : Get time slots, freeBusyType=FREE or BUSY-TENTATIVE
av -> ODA : FHIR service returns a bundle of Schedules.

ODA -> ODA : Search bundle data for slots of \nfreeBusyType = FREE or BUSY-TENTATIVE
note right: Slots that are freeBusyType = BUSY-TENTATIVE but too old,\n\
 ie. more than 5 minutes, or freeBusyType = BUSY \n\
 but not status = booked, are written as freeBusyType = FREE.

ODA -> av : Write appointment status = pending\n\
 (or status = booked if "pending" is not supported by target system)
av -> EHR : Write slot as freeBusyType = BUSY-TENTATIVE\n\
 (or freeBusyType = BUSY if not supported by target system)

ODA -> Client : Print pending Appointments to user
Client -> ODA : Confirm

ODA -> av : Write Appointment status = booked
av -> EHR : write slot as freeBusyType = BUSY

@enduml
