@startuml
!includeurl https://raw.githubusercontent.com/omahoito/rfc/master/Styles.iuml
footer
KaPa architecture diagram generated with plantuml.com to github.com/omahoito/definitions. \
CC-BY-4.0 City of Espoo 2017. \
To change the picture, make a pull request with changes to kapa.plantuml and README.md.
endfooter

actor Browser

folder "External Services" {
    component KaPa
    component EHR
    component ESB
}

folder ODA {
    folder "ODA DMZ" {
        component "API Gateway" as gw
        component "oda-esb" as esb
        component "Security Server" as sec
    }
    folder "ODA VLAN" {
        component "ODA services" as x
    }
}

Browser --> gw
gw --> x

x --> esb
x --> EHR
esb <--> sec
esb <--> ESB
sec <--> KaPa
esb --> gw

@enduml
