@startuml
!includeurl https://raw.githubusercontent.com/omahoito/rfc/master/Styles.iuml
header
Module diagram generated with plantuml.com to github.com/omahoito/definitions. \
CC-BY-4.0 City of Espoo 2017. \
To change the picture, make a pull request with changes to modules.plantuml and README.md.
endheader

agent browser
folder "ODA 2" {
    component "oda-web-front" as owf
    component dashboard
    component "oda-backend" as ob
    component "oda-idp" as idp
    component "oda-esb" as esb
    component "oda-fhir-service" as ofs
    component "oda-logging-service" as ols
    component "oda-phr" as op
    component "oda-analytics-service" as oas
    component "oda-notification-service" as ons
    component "oda-cds-service" as ocds
    database "PostgreSQL" as postgres
    database "MongoDB" as mongo

    browser --> owf
    browser --> dashboard
    owf --> ob
    owf --> idp
    ob --> ofs
    ob --> ols
    ofs --> op
    ofs --> ols
    ofs <--> esb
    ofs --> ocds
    ofs --> ons
    op --> ols
    op --> postgres
    ols --> mongo
    oas --> ols
    ocds --> op
    ons --> op
    dashboard --> oas
    idp --> op
}

folder "External systems" as ext {
    component "Suomi.fi\ne-Identification" as eident
    component "Suomi.fi\nData Exchange Layer" as del
    component AVPH
}

idp --> eident
esb <--> del
ofs --> AVPH

folder "ODA 1" {
    component "Questionnaire\ndatabase" as VKT
    component "ODA 1 API gateway" as ODA1
    component "EBMeDS\nDecision support system" as EBMeDS
    ODA1 --> EBMeDS
}

VKT --> ob
ofs --> ODA1

@enduml
