@startuml
header
Sequence diagram for first login
endheader

participant ODA_WEB_UI
participant ODA_FHIR_API

box "ODA 2" #LightBlue
    participant ODA_WEB_UI
    participant ODA_FHIR_API
end box
participant ODA_PHR
participant SUOMIFI_IDP
ODA_WEB_UI <-- ODA_WEB_UI: GET [oda-backend-base]/api/login
ODA_WEB_UI -> SUOMIFI_IDP:  HTTP 302 Found [Redirect to Suomi.fi IDP]
ODA_WEB_UI <-- SUOMIFI_IDP: Authenticate and return HETU from VRK

ODA_WEB_UI -> ODA_FHIR_API: GET [oda-fhir-base]/Patient/$searchbynationalid?nationalid=HETU
ODA_FHIR_API -> ODA_PHR: GET [oda-phr-base]/Person?identifier=HETU
ODA_FHIR_API <-- ODA_PHR: HTTP 200 OK [Empty bundle - person not found]
ODA_WEB_UI <-- ODA_FHIR_API: HTTP 200 OK [Empty bundle - patient not found]

ODA_WEB_UI -> ODA_WEB_UI: Accept terms and conditions


ODA_WEB_UI -> ODA_FHIR_API: POST [oda-fhir-base]/Patient/$createaccount

ODA_FHIR_API -> ODA_PHR: POST [oda-phr-base]/
ODA_FHIR_API <-- ODA_PHR: HTTP 200 OK [Bundle with transaction results]
 
ODA_WEB_UI <-- ODA_FHIR_API: HTTP 200 OK [Bundle with transaction results]

@enduml

'POST http://fhir.example.com/Patient/$everything